version: "3.9"
services:
  app:
    build:./app
    ports:
      - "5000:5000"
  settlement-system:
    build:./settlement-system
    ports:
      - "5001:5001"
  tokenization-api:
    build:./tokenization-api
    ports:
      - "5002:5002"
  ml-scoring-api:
    build:./ml-scoring-api
    ports:
      - "5003:5003"
  3ds-server:
    build:./3ds-server
    ports:
      - "5004:5004"
